### ISSUE TITLE
Debian init script should go in /etc/init.d

### ISSUE THREAD

**Issue by bhagemeier** [EGI-FCTF/glancepush#1]
Debian does not know anything about /etc/rc.d
However, I found hints about RedHat based distros symlinking /etc/rc.d/init.d as /etc/init.d, which implies that /etc/init.d may be a good, generic solution.

**Comment by mpuel** [comment]
Right, I am just used to write RHEL system rc scripts :) I moved it (as for osssm). I do not update the binaries, but it will be integrated in next release.  Cheers.
